simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('users/', views.UserList.as_view(),name="users"),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(),name='signup'),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/',views.CreatePost.as_view(), name='create'),
    path('by/<username>/',views.UserPost.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('posts/',include('posts.urls', namespace='posts')),
    path('groups/',include('groups.urls', namespace='groups')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(),name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% comment %} <meta http-equiv="X-UA-Compatible" content="IE=edge"> {% endcomment %}
    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% endcomment %}
    <title>bookface</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static '/simplesocial/css/master.css' %}">
</head>
<body>

    <nav class="navbar navbar-expand navbar-dark top-bar" role="navigation" id="navbar">
        <div class="container">
            <a class='navbar-brand mynav' href="{% url 'home' %}"><strong>bookface</strong></a>
            <ul class="navbar-nav ml-auto navigation">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link navi" href="{% url 'posts:create' %}">Post</a></li>
                    <li class="nav-item"><a class="nav-link navi" href="{% url 'groups:all' %}">Groups</a></li>
                    <li class="nav-item"><a class="nav-link navi" href="{% url 'groups:create' %}">Create Group</a></li>
                    <li class="nav-item"><a class="nav-link navi" href="{% url 'accounts:users' %}">Users</a></li>
                    <li class="nav-item"><a class="nav-link navi" href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link navi" href="{% url 'accounts:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link navi" href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mycontent"></div>
        {% block content %}
        
        {% endblock content %}
    </div>
</body>
<script type="text/javascript" src="{% static '/simplesocial/js/master.js' %}"></script>
</html>

simplesocial/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container col-md-8 main-index">
        <h3>Welcome to <strong>bookface</strong></h1>
    </div>
    <div class="container col-md-8 main-index">
        <p>
            This page is just a simple html/css + django web to showcase/test some code. <br>
            You can signup to this page in order to create and view groups and add posts to groups. 
            While writing posts you can use simple html tags to include formatting and or images or other content.
        </p>
    </div>

{% endblock content %}

simplesocial/templates/test.html
{% extends 'base.html' %}

{% block content %}
    <div class="container col-md-12 userlog">
        <h1>You are now logged in</h1>
    </div>

{% endblock content %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}

{% block content %}

    <div class="container col-md-12 userlog">
        <h1>Thanks for visiting, come back soon!</h1>
    </div>

{% endblock content %}