simplesocial/groups/urls.py
from django.urls import path
from . import views

app_name='groups'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug>/', views.SingleGroup.as_view(),name='single'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave'),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/',views.CreatePost.as_view(), name='create'),
    path('by/<username>/',views.UserPost.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('posts/',include('posts.urls', namespace='posts')),
    path('groups/',include('groups.urls', namespace='groups')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(),name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

simplesocial/groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django import template


# Create your models here.
User = get_user_model()
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(self.name)
        self.description_html = self.description
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ['name']

    

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

simplesocial/groups/views.py
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from groups.models import Group, GroupMember
from . import models

# Create your views here.

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs) -> str:
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request,"Warning already a member!")
        else:
            messages.success(self.request,"You are now a memeber")
        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs) -> str:
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug = self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,"Sorry you are not in this group!")
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')
        return super().get(request, *args, **kwargs)
    

simplesocial/groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}

    <div class="group-page">
        <div class="container">
            <div class="row">
                {% block pregroup %}{% endblock pregroup %}
                {% block group_content %}{% endblock group_content %}
                {% block postgroup %}{% endblock postgroup %}
            </div>
        </div>
    </div>


{% endblock content %}

simplesocial/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    <div class="container">
        <h1 class="group-name"><strong>{{ group.name }}</strong></h1>
        <h3 class="group-desc">{{group.description|safe}}</h3>
        <h4>Member count: {{ group.members.count }}</h4>
    </div>
    <hr>

    <div class="col-md-12">
        {% if user in group.members.all %}
            <p>You are a member of this group</p>
            <a class="btn btn-danger" href="{% url 'groups:leave' slug=group.slug %}">Leave group</a>
        {% else %}
            <p>You are not a member of this group</p>
            <a class="btn btn-success" href="{% url 'groups:join' slug=group.slug %}">Join group</a>
        {% endif %}
    </div>

{% endblock pregroup %}

{% block group_content %}

    <div class="col-md-12 content h-100 p-5 bg-light border rounded-3">
        {% if group.posts.count == 0 %}
            <h2>No posts in this group yet!</h2>
        {% else %}
            {% for post in group.posts.all %}
                <div>
                    {% include "posts/_post.html" %}
                </div>
            {% endfor %}
        {% endif %}

    </div>

{% endblock group_content %}

simplesocial/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block group_content %}

    <h4>Create a new group!</h4>

    <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Create">
    </form>

{% endblock group_content %}

simplesocial/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    {% if user.is_authenticated %}
        <div class="col-md-4">
            <div class="content">
                {% if user.is_authenticated %}
                    <h2>
                        Welcome back <br>
                        <a class="user" href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
                    </h2>
                {% endif %}
                <hr>
                <h2>Groups</h2>
                <p>Welcome to the groups page</p>
            </div>
            {% if user.is_authenticated %}
                <a class="btn btn-warning" href="{% url 'groups:create' %}">Create new group</a>
            {% endif %}
        </div>
    {% else %}
        <div class="col-md-12 main-groups-list">
            <h3>Please login or signup to view this page</h3>
        </div>
    {% endif %}
{% endblock pregroup %}

{% block group_content %}
    {% if user.is_authenticated %}
        <div class="col-md-8">
            <div class="list-group">
                {% for group in object_list %}
                    <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
                        <h3 class="title list-group-item-heading">{{group.name}}</h3>
                        <div class="list-group-item-next container-fluid">
                            {{group.description|safe}}
                            <div class="row">
                                <div class="col-md-4">
                                    <span class="badge bg-secondary">{{group.members.count}}</span>
                                    member{{group.memebers.count|pluralize}}
                                </div>
                                <div class="col-md-4">
                                    <span class="badge bg-secondary">{{group.posts.count}}</span>
                                    post{{group.posts.count|pluralize}}
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    {% endif %}

{% endblock  %}